export enum Headings {
  NORMAL = "Normal",
  TITLE = "Title",
  HEADING_1 = "Heading 1",
  HEADING_2 = "Heading 2",
  HEADING_3 = "Heading 3",
  HEADING_4 = "Heading 4",
  HEADING_5 = "Heading 5",
  HEADING_6 = "Heading 6",
}

export enum TextFontFamily {
  ROBOTO = "Roboto",
  POPPINS = "Poppins",
}

export enum TextAlign {
  LEFT = "left",
  CENTER = "center",
  RIGHT = "right",
  JUSTIFY = "justify",
}

export const colors = [
  "#1578D0",
  "#3EC064",
  "#D4A809",
  "#109FC0",
  "#6167E4",
  "#9CA3AF",
  "#FF3434",
  "#111111",
];

export const backgroundColors = [
  "#1578D0",
  "#3EC064",
  "#D4A809",
  "#109FC0",
  "#6167E4",
  "#9CA3AF",
  "#FF3434",
  "#111111",
];

export const emojis = [
  { emoji: "😀", name: "grinning_face" },
  { emoji: "😄", name: "grinning_face_with_closed_eyes" },
  { emoji: "😁", name: "beaming_face" },
  { emoji: "😆", name: "squinting_face" },
  { emoji: "😉", name: "winking_face" },
  { emoji: "😊", name: "smiling_face_with_closed_eyes" },
  { emoji: "🤩", name: "star_struck" },
  { emoji: "🤑", name: "money_mouth_face" },
  { emoji: "🤗", name: "hugging_face" },
  { emoji: "🤔", name: "thinking_face" },
  { emoji: "🫡", name: "saluting_face" },
  { emoji: "😏", name: "smirking_face" },
  { emoji: "🤠", name: "cowboy_face" },
  { emoji: "🥳", name: "partying_face" },
  { emoji: "😎", name: "smiling_face_with_sunglasses" },
  { emoji: "💌", name: "love_letter" },
  { emoji: "❤", name: "red_heart" },
  { emoji: "💛", name: "yellow_heart" },
  { emoji: "💚", name: "green_heart" },
  { emoji: "💙", name: "blue_heart" },
  { emoji: "💯", name: "100" },
  { emoji: "👋", name: "waving_hand" },
  { emoji: "👌", name: "ok_hand" },
  { emoji: "✌", name: "victory" },
  { emoji: "👈", name: "point_left" },
  { emoji: "👉", name: "point_right" },
  { emoji: "🖕", name: "middle_finger" },
  { emoji: "👇", name: "point_down" },
  { emoji: "👍", name: "thumbsup" },
  { emoji: "✊", name: "fist" },
  { emoji: "🤜", name: "right_facing_fist" },
  { emoji: "👏", name: "clapping_hands" },
  { emoji: "🙌", name: "raised_hands" },
  { emoji: "🤝", name: "handshake" },
  { emoji: "✍", name: "writing_hand" },
  { emoji: "💪", name: "right_bicep" },
  { emoji: "🧑‍🔧", name: "mechanic" },
  { emoji: "🌳", name: "deciduous_tree" },
  { emoji: "🌍", name: "earth_europe" },
  { emoji: "🌎", name: "earth_americas" },
  { emoji: "🌏", name: "earth_asia" },
  { emoji: "🏠", name: "house" },
  { emoji: "🚨", name: "rotating_light" },
  { emoji: "☀", name: "sun" },
  { emoji: "🌙", name: "crescent_moon" },
  { emoji: "⚡", name: "high_voltage" },
  { emoji: "🎖", name: "military_medal" },
  { emoji: "🏆", name: "trophy" },
  { emoji: "🏅", name: "sports_medal" },
  { emoji: "🥇", name: "first_place_medal" },
  { emoji: "🥈", name: "second_place_medal" },
  { emoji: "🥉", name: "third_place_medal" },
  { emoji: "🎯", name: "direct_hit" },
  { emoji: "💰", name: "moneybag" },
  { emoji: "💴", name: "yen" },
  { emoji: "✉", name: "envelope" },
  { emoji: "📧", name: "e-mail" },
  { emoji: "✒", name: "black_nib" },
  { emoji: "💼", name: "briefcase" },
  { emoji: "📅", name: "date" },
  { emoji: "📈", name: "chart_with_upwards_trend" },
  { emoji: "📉", name: "chart_with_downwards_trend" },
  { emoji: "📋", name: "clipboard" },
  { emoji: "📌", name: "pushpin" },
  { emoji: "📍", name: "round_pushpin" },
  { emoji: "🔧", name: "wrench" },
  { emoji: "🪜", name: "ladder" },
  { emoji: "🚫", name: "no_entry" },
  { emoji: "⚠", name: "warning" },
  { emoji: "🔚", name: "end" },
  { emoji: "✅", name: "white_check_mark" },
  { emoji: "❌", name: "cross_mark" },
  { emoji: "🆒", name: "cool" },
  { emoji: "🆗", name: "ok" },
  { emoji: "🆚", name: "vs" },
  { emoji: "🔴", name: "red_circle" },
  { emoji: "🟡", name: "yellow_circle" },
  { emoji: "🟢", name: "green_circle" },
  { emoji: "🚩", name: "triangular_flag_on_post" },
];
